In [1]:
# This is the first version of the TakeHomeExam. The following questions will be added until Friday 


In [ ]:
# Define the necessary packages

%matplotlib inline

import numpy as np
import matplotlib as mpl
import matplotlib.pylab as plt


In [6]:
# Define data in the following array format

data = np.array([[0,0,-1.064],
[0,1,-0.904],
[0,5,0.532],
[1,0,1.192],
[1,2,0.010],
[1,3,0.340],
[2,0,4.417],
[2,1,2.141],
[2,2,-0.260],
[2,3,1.039],
[2,4,1.633],
[2,5,0.031],
[3,1,1.811],
[3,3,0.619],
[3,4,0.386],
[3,5,0.577],
[4,1,-1.467],
[4,2,1.323],
[4,4,0.516],
[4,5,-0.949]])

print(data)


[[ 0.     0.    -1.064]
 [ 0.     1.    -0.904]
 [ 0.     5.     0.532]
 [ 1.     0.     1.192]
 [ 1.     2.     0.01 ]
 [ 1.     3.     0.34 ]
 [ 2.     0.     4.417]
 [ 2.     1.     2.141]
 [ 2.     2.    -0.26 ]
 [ 2.     3.     1.039]
 [ 2.     4.     1.633]
 [ 2.     5.     0.031]
 [ 3.     1.     1.811]
 [ 3.     3.     0.619]
 [ 3.     4.     0.386]
 [ 3.     5.     0.577]
 [ 4.     1.    -1.467]
 [ 4.     2.     1.323]
 [ 4.     4.     0.516]
 [ 4.     5.    -0.949]]


In [ ]:
# Define a suitable error function to measure the size of the error as a function of the parameters w and h.



In [ ]:
# Take the derivative of the total error with respect to each parameter w_{i,k} and h_{k,j} and
# implement a function that computes the derivative of the total error with respect to each parameter.




In [ ]:
# Print the predictions of the model for the defined indices
